/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: number.i

package number

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_example_cc09b711e35ee690(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_example_cc09b711e35ee690(swig_intgo arg1);
extern uintptr_t _wrap_new_Number_example_cc09b711e35ee690(void);
extern void _wrap_delete_Number_example_cc09b711e35ee690(uintptr_t arg1);
extern void _wrap_Number_SetNumber_example_cc09b711e35ee690(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_Number_Print_example_cc09b711e35ee690(uintptr_t arg1);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_example_cc09b711e35ee690(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_example_cc09b711e35ee690(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrNumber uintptr

func (p SwigcptrNumber) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrNumber) SwigIsNumber() {
}

func NewNumber() (_swig_ret Number) {
	var swig_r Number
	swig_r = (Number)(SwigcptrNumber(C._wrap_new_Number_example_cc09b711e35ee690()))
	return swig_r
}

func DeleteNumber(arg1 Number) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_Number_example_cc09b711e35ee690(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrNumber) SetNumber(arg2 int) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_Number_SetNumber_example_cc09b711e35ee690(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
}

func (arg1 SwigcptrNumber) Print() {
	_swig_i_0 := arg1
	C._wrap_Number_Print_example_cc09b711e35ee690(C.uintptr_t(_swig_i_0))
}

type Number interface {
	Swigcptr() uintptr
	SwigIsNumber()
	SetNumber(arg2 int)
	Print()
}
